template<class Expect> static void LabelEditorCases(Application& app,Application::View& v,Expect expect){
    auto& state=app.state_;app.active_=true;app.diagnostic_session_=true;app.toolbar_monitor_=v.bounds;
    app.Command(14);app.toolbar_transition_.Reset(1);app.UpdateToolbar({450,400});state.number_combo=NumberCombo::Leader;
    app.Command(81);Pump();expect(app.edit_&&app.edit_badge_label_&&!(GetWindowLongPtrW(app.edit_,GWL_STYLE)&ES_MULTILINE),"number property opens a native single-line label editor");if(!app.edit_)return;
    GUITHREADINFO gui{sizeof(gui)};GetGUIThreadInfo(GetCurrentThreadId(),&gui);expect(gui.hwndFocus==app.edit_&&gui.hwndCaret==app.edit_,"label field owns native caret and focus above DXGI overlay");
    expect(SendMessageW(app.edit_,EM_GETLIMITTEXT,0,0)==NumberLabelLimit,"native label input limits short labels to 64 UTF-16 units");
    SendMessageW(app.edit_,EM_REPLACESEL,TRUE,reinterpret_cast<LPARAM>(L"登录入口"));
    SendMessageW(app.edit_,WM_IME_STARTCOMPOSITION,0,0);Key(app.edit_,VK_RETURN);expect(app.edit_&&app.edit_composing_,"IME candidate Enter does not prematurely commit the badge label");
    SendMessageW(app.edit_,WM_IME_ENDCOMPOSITION,0,0);Pump();expect(app.edit_&&!app.edit_composing_,"IME composition completion keeps focused label editor open");
    const std::filesystem::path folder=L"build/number-label-preview";std::filesystem::create_directories(folder);SavePng(Preview(app),folder/L"label-input-light.png");
    Key(app.edit_,VK_RETURN);expect(!app.edit_&&state.number_label==L"登录入口"&&app.document_.marks.empty()&&!app.document_.CanUndo(),"editing default label sets tool property without creating an annotation");
    app.Command(81);SetWindowTextW(app.edit_,L"取消这次修改");Key(app.edit_,VK_ESCAPE);expect(state.number_label==L"登录入口","Escape preserves the prior default custom label");
    app.Command(81);SetWindowTextW(app.edit_,L"步骤 A");const auto button=app.edit_frame_->ButtonRect();const HWND frame=app.edit_frame_->Window();const LPARAM at=MAKELPARAM((button.left+button.right)/2,(button.top+button.bottom)/2);SendMessageW(frame,WM_LBUTTONDOWN,MK_LBUTTON,at);SendMessageW(frame,WM_LBUTTONUP,0,at);
    expect(!app.edit_&&state.number_label==L"步骤 A","rounded editor return button commits custom label");
    auto original=NumberFixture(NumberCombo::Leader,true);original.number=7;original.rotation=30;app.document_.Reset();app.document_.marks={original};app.document_.selected=0;state.tool=Tool::Select;app.SyncSelectedProperties();app.toolbar_transition_.Reset(1);app.UpdateToolbar({450,400});
    app.Command(81);expect(app.edit_index_==0&&app.edit_badge_label_,"selected number property edits its own label rather than its description");SetWindowTextW(app.edit_,L"确认并提交");Key(app.edit_,VK_RETURN);
    const auto changed=app.document_.marks[0];expect(changed.number_label==L"确认并提交"&&changed.text==original.text&&NumberAttached(changed)&&Near(WorldPoint(changed,changed.number_target),WorldPoint(original,original.number_target)),"native label commit widens and reconnects a rotated badge while keeping description and target");
    const auto selectNumber=[&]{const auto p=WorldPoint(app.document_.marks[0],BadgeCenter(app.document_.marks[0]));app.PointerDown(v,p);app.PointerUp(v,p);app.toolbar_transition_.Reset(1);app.UpdateToolbar({450,400});};
    app.Command(7);expect(app.document_.marks[0]==original&&!app.document_.CanUndo(),"label edit is exactly one undo step");selectNumber();expect(state.number_label.empty(),"reselecting after undo shows automatic numbering in the property input");app.Command(8);selectNumber();expect(app.document_.marks[0]==changed&&state.number_label==changed.number_label,"reselecting after redo synchronizes label input and connected geometry");
    app.document_.Reset();app.document_.marks={changed};app.document_.selected=0;app.SyncSelectedProperties();app.Command(81);Key(app.edit_,VK_RETURN);expect(app.document_.marks[0]==changed&&!app.document_.CanUndo(),"confirming an unchanged label adds no undo history");
    app.Command(81);SetWindowTextW(app.edit_,L" ");Key(app.edit_,VK_RETURN);expect(app.document_.marks[0].number_label.empty()&&NumberCaption(app.document_.marks[0])==L"7"&&app.document_.marks[0].text==original.text,"clearing input restores the original automatic number without deleting the mark");
    app.Command(7);selectNumber();app.Command(81);expect(app.edit_&&app.edit_badge_label_,"reselected number reopens its label after undo");if(!app.edit_)return;SetWindowTextW(app.edit_,L"不应保存");Key(app.edit_,VK_ESCAPE);expect(app.document_.marks[0]==changed&&!app.document_.CanUndo(),"canceling selected label leaves both document and history unchanged");
    state.dark=true;app.Command(81);expect(app.edit_&&app.edit_frame_,"dark label editor opens before message pump");if(!app.edit_)return;SetWindowTextW(app.edit_,L"确认提交");Pump();expect(app.edit_&&app.edit_frame_,"dark label editor retains focus after pending window messages");if(!app.edit_)return;SavePng(Preview(app),folder/L"label-input-dark.png");SetFocus(v.window);Pump();expect(!app.edit_&&app.document_.marks[0].number_label==L"确认提交","focus loss commits native label input");
    app.PointerDoubleClick(v,WorldPoint(app.document_.marks[0],BadgeCenter(app.document_.marks[0])));expect(app.edit_&&app.edit_badge_label_,"double-clicking a numbered badge reopens its custom label");app.CommitText(true);
    auto note=NumberFixture(NumberCombo::Text,true);note.number_label=L"说明";FitNumberBadge(note);ReconnectNumberBadge(note);app.document_.Reset();app.document_.marks={note};app.document_.selected=0;state.tool=Tool::Select;app.SyncSelectedProperties();app.BeginText(v,note.a,0);
    expect(app.edit_&&!app.edit_badge_label_&&(GetWindowLongPtrW(app.edit_,GWL_STYLE)&ES_MULTILINE),"description editor remains independent and multiline");SetWindowTextW(app.edit_,L"这里是独立说明文字");Key(app.edit_,VK_RETURN);expect(app.document_.marks[0].number_label==L"说明"&&app.document_.marks[0].text==L"这里是独立说明文字","description editing does not overwrite the badge label");
    state.toolbar.scale=2;const auto saved=v.bounds;v.bounds={40,40,520,640};app.BeginText(v,{500,620},0,true);RECT panel{};GetWindowRect(app.edit_frame_->Window(),&panel);expect(panel.left>=v.bounds.left&&panel.right<=v.bounds.right&&panel.top>=v.bounds.top&&panel.bottom<=v.bounds.bottom,"label popup fits a narrow high-DPI monitor near screen edges");app.CommitText(true);v.bounds=saved;
    Renderer renderer;SavePng(renderer.Demo(true,false,Tool::Number),folder/L"number-toolbar.png");
}
