#include "recording/core.h"
#include "recording/encoder.h"
#include <psapi.h>
#include <iostream>
#include <condition_variable>
#include <mutex>
using namespace lumashot::recording;
unsigned long long Time(FILETIME t){ULARGE_INTEGER n{};n.LowPart=t.dwLowDateTime;n.HighPart=t.dwHighDateTime;return n.QuadPart;}
int main(){CoInitializeEx(nullptr,COINIT_MULTITHREADED);MFStartup(MF_VERSION);int result=0;
    try{const auto file=std::filesystem::current_path()/L"recording-test-output"/L"1080p-audio.mp4";std::filesystem::create_directories(file.parent_path());FILETIME create{},exit{},kernel{},user{};GetProcessTimes(GetCurrentProcess(),&create,&exit,&kernel,&user);const auto cpu_start=Time(kernel)+Time(user);const auto start=std::chrono::steady_clock::now();std::mutex mutex;std::condition_variable changed;bool done=false;Status final;SIZE_T warm{},last{},peak{};
        Session session;Options options;options.synthetic=true;options.synthetic_size={1920,1080};options.synthetic_frames=600;options.system_audio=true;options.fps=30;options.width=1920;
        session.Start(options,file,[&](Status status){PROCESS_MEMORY_COUNTERS_EX memory{};memory.cb=sizeof(memory);GetProcessMemoryInfo(GetCurrentProcess(),reinterpret_cast<PROCESS_MEMORY_COUNTERS*>(&memory),sizeof(memory));if(status.frames>=120){if(!warm)warm=memory.PrivateUsage;last=memory.PrivateUsage;peak=std::max(peak,last);}if(status.state==State::Preview||status.state==State::Failed){std::lock_guard lock(mutex);final=std::move(status);done=true;changed.notify_one();}});
        {std::unique_lock lock(mutex);if(!changed.wait_for(lock,std::chrono::seconds(40),[&]{return done;})){session.Stop();throw std::runtime_error("Benchmark timeout");}}
        if(final.state!=State::Preview){const int bytes=WideCharToMultiByte(CP_UTF8,0,final.detail.c_str(),-1,nullptr,0,nullptr,nullptr);std::string text(size_t(bytes),0);WideCharToMultiByte(CP_UTF8,0,final.detail.c_str(),-1,text.data(),bytes,nullptr,nullptr);throw std::runtime_error(text);}
        GetProcessTimes(GetCurrentProcess(),&create,&exit,&kernel,&user);const auto seconds=std::chrono::duration<double>(std::chrono::steady_clock::now()-start).count();SYSTEM_INFO info{};GetSystemInfo(&info);const auto cpu=100.*double(Time(kernel)+Time(user)-cpu_start)/10000000./seconds/info.dwNumberOfProcessors;
        std::cout<<"1080p30 GPU synthetic + AAC, frames="<<final.frames<<", dropped="<<final.dropped<<", wall_seconds="<<seconds<<", total_CPU_percent="<<cpu<<", warm_private_MiB="<<warm/1048576.<<", final_private_MiB="<<last/1048576.<<", peak_private_MiB="<<peak/1048576.<<std::endl;
        if(final.frames!=600||peak>warm+24*1024*1024)throw std::runtime_error("Recording failed frame count or bounded-memory check");std::cout<<"PASS 20 second recording has bounded post-warmup private memory"<<std::endl;
        ComPtr<IMFSourceReader> reader;Check(MFCreateSourceReaderFromURL(file.c_str(),nullptr,&reader),"Read audio output");reader->SetStreamSelection(DWORD(MF_SOURCE_READER_ALL_STREAMS),FALSE);reader->SetStreamSelection(DWORD(MF_SOURCE_READER_FIRST_AUDIO_STREAM),TRUE);ComPtr<IMFMediaType> type;MFCreateMediaType(&type);type->SetGUID(MF_MT_MAJOR_TYPE,MFMediaType_Audio);type->SetGUID(MF_MT_SUBTYPE,MFAudioFormat_PCM);Check(reader->SetCurrentMediaType(DWORD(MF_SOURCE_READER_FIRST_AUDIO_STREAM),nullptr,type.Get()),"Decode AAC output");bool audible=false;unsigned samples=0;for(int i=0;i<100;++i){DWORD flags{};ComPtr<IMFSample> sample;Check(reader->ReadSample(DWORD(MF_SOURCE_READER_FIRST_AUDIO_STREAM),0,nullptr,&flags,nullptr,&sample),"Decode tone");if(flags&MF_SOURCE_READERF_ENDOFSTREAM)break;if(!sample)continue;ComPtr<IMFMediaBuffer> buffer;sample->ConvertToContiguousBuffer(&buffer);BYTE* bytes{};DWORD length{};buffer->Lock(&bytes,nullptr,&length);for(DWORD j=0;j<length/2;++j)if(std::abs(reinterpret_cast<short*>(bytes)[j])>100)audible=true;buffer->Unlock();++samples;}if(!audible||!samples)throw std::runtime_error("Encoded synthetic tone missing");std::cout<<"PASS AAC audio decodes to the generated synthetic tone"<<std::endl;
    }catch(const std::exception& e){std::cerr<<e.what()<<std::endl;result=1;}MFShutdown();CoUninitialize();return result;
}
